---
# Copyright 2017 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: lxc-update.yml
  hosts: localhost
  gather_facts: yes
  environment: "{{ deployment_environment }}"
  vars:
    os_image_links:
      - name: ubuntu-14.04.5-server-amd64
        images:
          - url: "http://releases.ubuntu.com/14.04.5/ubuntu-14.04.5-server-amd64.iso"
            dest: "{{ project_path_local }}/os_images/ubuntu-14.04.5-server-amd64.iso"
            sha1sum: 5e567024c385cc8f90c83d6763c6e4f1cd5deb6f
      - name: ubuntu-14.04.5-server-ppc64el
        images:
          - url: "http://cdimage.ubuntu.com/releases/14.04.5/release/ubuntu-14.04.5-server-ppc64el.iso"
            dest: "{{ project_path_local }}/os_images/ubuntu-14.04.5-server-ppc64el.iso"
            sha1sum: f4843944ca1927375bd3a0dbeb744f5764876dae
          - url: "http://us.ports.ubuntu.com/dists/trusty-updates/main/installer-ppc64el/20101020ubuntu318.41/images/xenial-netboot/mini.iso"
            dest: "{{ project_path_local }}/os_images/ubuntu-14.04.5-server-ppc64el.mini.iso"
            sha1sum: b167507d2a65fa81f199cd2125079beb499023c6
      - name: ubuntu-16.04.3-server-amd64
        images:
          - url: "http://releases.ubuntu.com/16.04/ubuntu-16.04.3-server-amd64.iso"
            dest: "{{ project_path_local }}/os_images/ubuntu-16.04.3-server-amd64.iso"
            sha1sum: f3532991e031cae75bcf5e695afb844dd278fff9
      - name: ubuntu-16.04.3-server-ppc64el
        images:
          - url: "http://cdimage.ubuntu.com/releases/16.04.3/release/ubuntu-16.04.3-server-ppc64el.iso"
            dest: "{{ project_path_local }}/os_images/ubuntu-16.04.3-server-ppc64el.iso"
            sha1sum: 3048e855b83787a23dc7fdd7e72496e264059d44
  tasks:
    - name: "Read {{ config_local }}"
      include_vars:
        name: config
        file: "{{ config_local }}"

    - name: "Get list of OS images from config.yml"
      set_fact:
        os_image_list: "{{ item.os.profile }}"
      with_items:
        - "{{ config.node_templates }}"
      when:
        - item.os.profile is defined
        - item.os.profile is not none

    - name: "Loop through both lists"
      set_fact:
        images: "{{ item[0].images }}"
      with_nested:
        - "{{ os_image_links }}"
        - "{{ os_image_list }}"
      when: ( item[0].name == (item[1]|splitext)[0] ) or
            ( item[0].name == item[1] )
      register: image_list

    - name: "Compile results into single list with unique entries"
      set_fact:
        image_list_unique:
          "{{ image_list.results | selectattr('ansible_facts', 'defined') | \
           map(attribute='ansible_facts.images') | list | unique }}"

    - name: "Download OS installer images"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        force: no
        checksum: "sha1:{{ item.sha1sum }}"
      with_items: "{{ image_list_unique }}"

- hosts: deployer
  environment: "{{ deployment_environment }}"
  vars:
    scripts_path_local: "{{ hostvars.localhost.scripts_path_local }}"
    images_local: "{{ hostvars.localhost.project_path_local }}/os_images"
    config_local: "{{ hostvars.localhost.config_local }}"
  tasks:
    - name: "Print local scripts/config paths"
      debug:
        msg: "{{ item }}"
      with_items:
        - "Local Scripts Path: {{ scripts_path_local }}"
        - "Local Config file: {{ config_local }}"

    - name: "RHEL/CentOS: Fix selinuxfs being mounted read-write in the chroot"
      mount:
        name: /sys/fs/selinux
        state: mounted
        src: selinuxfs
        fstype: selinuxfs
        opts: remount,ro
      when: hostvars.localhost.ansible_distribution in ['RedHat','CentOS']
      become: yes
      become_method: sudo

    - name: "Copy OS images and configs into deployment container"
      synchronize:
        src: "{{ images_local }}"
        dest: "{{ project_path }}"

    - name: "Create log file"
      file:
        path: "{{ project_path }}/log.txt"
        state: touch
        mode: 0644
